apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minecraft-server
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - client: cliente-945b3565-manoel
            port: 43452
          - client: cliente-23435678-raimundo
            port: 43453
  template:
    metadata:
      name: minecraft-{{client}}
    spec:
      project: default
      source:
        repoURL: https://github.com/mjrdev/minecraft-server-k8s
        targetRevision: main
        path: .
        helm:
          values: |
            client:
              name: {{client}}
      destination:
        server: https://kubernetes.default.svc
        namespace: minecraft
      syncPolicy:
        automated:
          prune: true
          selfHeal: true